test main push

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,15 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npx lint-staged
+# 获取当前分支名
+branch=$(git symbolic-ref --short HEAD)
+
+# 如果为main分支,退出并返回码1表示错误
+if [ "$branch" = "main" ]; then
+    echo "Cannot commit directly to main branch"
+    exit 1
+fi
+
+# 否则继续执行提交
+
+# npx lint-staged
